In [1]:
import numpy as np
w = np.random.uniform(-0.1, 0.1,(5,5))
print(w)
zero_test=np.zeros((5,2))
print(zero_test)

[[-0.01116957 -0.09272501  0.04801902 -0.0281906  -0.04023617]
 [ 0.00800102 -0.01240495  0.09164922  0.08141696 -0.02535758]
 [ 0.09401783 -0.0785074  -0.0418755  -0.02848039  0.03460124]
 [-0.04430066 -0.02295652 -0.07455604 -0.03334228 -0.09940499]
 [ 0.07272107 -0.05034467  0.05998523  0.07248235  0.07627085]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
q=np.random.uniform(-0.1,0.1,(5,2))
print(q)
mult=np.dot(w,q)
print(mult)

[[-0.03698479  0.01032783]
 [ 0.0237863   0.05155368]
 [-0.07703839 -0.01279532]
 [-0.00073253  0.0481352 ]
 [-0.06306484  0.06893256]]
[[-0.00293365 -0.00964063]
 [-0.00611196  0.00044149]
 [-0.00427987 -0.00152629]
 [ 0.01312946 -0.00914423]
 [-0.01337136  0.00613456]]


In [6]:
from activators import SigmoidActivator
activator=SigmoidActivator()
result=activator.forward(zero_test)
print(result)

[[0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]
 [0.5 0.5]]
